# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1liD9NsnmaZlMEYF5xICK1dQZAfUhYpW7
"""

import pandas as pd
data=pd.read_csv('Combined Data.csv',index_col=0)
data.head()

data = data.dropna()

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE

X_train, X_test, y_train, y_test = train_test_split(data['statement'], data['status'], test_size=0.2, random_state=42)

vectorizer = TfidfVectorizer(max_features=5000)
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_vectorized, y_train)

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_resampled, y_train_resampled)

y_pred = clf.predict(X_test_vectorized)
print(classification_report(y_test, y_pred))

new_sentences = ["oh my gosh", "Everything is great today"]
new_sentences_vectorized = vectorizer.transform(new_sentences)
predictions = clf.predict(new_sentences_vectorized)
print(predictions)